# Generated by Django 5.1.3 on 2024-11-23 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_tarea_archivo_tarea_titulo_alter_tarea_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurso',
            name='asignatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cursoasignatura'),
        ),
    ]
