# Generated by Django 5.1.3 on 2024-11-23 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_foro_asignatura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='asignatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cursoasignatura'),
        ),
    ]
